# Render config for the Astralith project
services:
  - type: web
    name: astralith-api
    runtime: node
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    plan: free
    envVars:
      - key: BUN_VERSION
        value: "1.2.4"
        sync: false
      - key: CLERK_SIGNING_SECRET
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: "3004"
        sync: false
    region: oregon
    buildCommand: pnpm install --frozen-lockfile
    startCommand: pnpm start
    healthCheckPath: /health
    rootDir: apps/api
version: "1"
